language: node_js
node_js:
  - "stable"
cache:
  npm: false
  directories:
    - node_modules
    - ~/.cache
install:
  - npm install
before_script: 
  - npm start --silent &
script:
  - npm run cypress:run --record --key $recordKey 
