language: node_js
node_js:
  - "stable"
cache:
  npm: true
  directories:
    - node_modules
    - ~/.cache
install:
  - npm ci
before_script: 
  # - npm install
  - npm start --silent &
script:
  - npm run cypress:run
  - $(npm bin)/cypress run
  - npm run build
 
